apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-listener-deployment
  labels:
    app: tcp-listener
spec:
  replicas: 
  selector:
    matchLabels:
      app: tcp-listener
  template:
    metadata:
      labels:
        app: tcp-listener
    spec:
      containers:
      - name: tcp-listener
        image: tcp-listener
        imagePullPolicy: Never
        ports: 
        - containerPort: 7878
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-listener-service
spec:
  selector:
    app: tcp-listener
  ports:
  - protocol: TCP
    port: 7879
    targetPort: 7878
